### ISSUE TITLE
signature Verification failed 

### ISSUE THREAD

**Issue by murugesanmadappan** [pmvr/python-hsslms#6]
this is my script file and i am getting signature Verification failed. Can you please help me on this. 

`import logging
from hsslms import HSS_Priv, LMS_ALGORITHM_TYPE, LMOTS_ALGORITHM_TYPE`

`# Configure the logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')`

`def main():
    # Define the LMS and LMOTS algorithm types
    lms_type = LMS_ALGORITHM_TYPE.LMS_SHA256_M24_H15
    lmots_type = LMOTS_ALGORITHM_TYPE.LMOTS_SHA256_N24_W4`

    # Log the algorithm types
    logging.info("LMS Algorithm Type: %s", lms_type)
    logging.info("LMOTS Algorithm Type: %s", lmots_type)

    # Initialize the HSS private key
    logging.info("Initializing HSS private key with LMS and LMOTS algorithm types.")
    hss_private_key = HSS_Priv([lms_type]*2, lmots_type)
    logging.debug("HSS private key initialized with LMS Type: %s and LMOTS Type: %s", lms_type, lmots_type)

    # Message to sign
    message = b"This is a Muru Secret message."
    logging.info("Message to be signed: %s", message)

    # Sign the message
    logging.info("Signing the message.")
    try:
        signature = hss_private_key.sign(message)
        logging.debug(f"Generated signature: {signature}")
    except Exception as e:
        logging.error("Error signing the message: %s", e)
        return

    # Verify the message
    logging.info("Verifying the message.")
    try:
        # Generate the public key data
        hss_public_key = hss_private_key.gen_pub()
        logging.debug("Public key data generated.")

        # Perform verification using the public key
        is_valid = hss_public_key.verify(message, signature)
        if is_valid:
            logging.info("Signature verification succeeded.")
        else:
            logging.warning("Signature verification failed.")
    except Exception as e:
        logging.error("Error verifying the message: %s", e)

if __name__ == "__main__":
    main()`

**Comment by pmvr** [comment]
Nothing wrong. Signature is valid.
An exception would have been raised if signature is invalid. 
For example: Try to change message in verify method.

**Comment by murugesanmadappan** [comment]
Thanks for you response. Working
